// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20181223061231_seeding-admin")]
    partial class SeedingAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountStatus");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DeletedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Username");

                    b.HasKey("AccountId");

                    b.ToTable("Account");

                    b.HasData(
                        new { AccountId = "ADMIN", AccountStatus = 1, CreatedAt = new DateTime(2018, 12, 23, 13, 12, 31, 613, DateTimeKind.Local), DeletedAt = new DateTime(2018, 12, 23, 13, 12, 31, 615, DateTimeKind.Local), Email = "admin@admin.com", Password = "bD1wo9lWUhncdeNzKpriLXOapoCdqmQzXBdV//UkNFs=", Salt = "8LK0MsWDvA4sawsyU+PotA==", UpdatedAt = new DateTime(2018, 12, 23, 13, 12, 31, 615, DateTimeKind.Local), Username = "ADMIN" }
                    );
                });

            modelBuilder.Entity("Backend.Models.PersonalInformation", b =>
                {
                    b.Property<string>("AccountId");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.HasKey("AccountId");

                    b.ToTable("PersonalInformation");

                    b.HasData(
                        new { AccountId = "ADMIN", Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), FirstName = "ADMIN", Gender = 2, LastName = "ADMIN" }
                    );
                });

            modelBuilder.Entity("Backend.Models.PersonalInformation", b =>
                {
                    b.HasOne("Backend.Models.Account", "Account")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("Backend.Models.PersonalInformation", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
